Executable         = MCscript.sh
Universe           = vanilla
notification       = Never
Input              = /dev/null
Arguments          = $(sim) $(filename) $(trigger) $(process)
Initialdir         = /sphenix/user/samfred/projects/gammajet/treemaking/macros
Output             = $(Initialdir)/MClog/$(process).out
Error              = $(Initialdir)/MClog/$(process).err
Log                = /tmp/samfred/MC$(process).log
PeriodicHold       = (NumJobStarts>=1 && JobStatus == 1)
job_lease_duration = 3600
request_memory     = 4096MB
#max_materialize    = 10000

Queue sim, filename, trigger from MCqueue.list
