Executable  = script.sh
Universe    = vanilla
notification= Never
Input       = /dev/null
Arguments       = $(runnumber) 
Initialdir    = /sphenix/user/samfred/projects/gammajet/treemaking/
Output    = $(Initialdir)/log/$(runnumber).out
Error     = $(Initialdir)/log/$(runnumber).err
Log       = /tmp/samfred/$(runnumber).log
PeriodicHold  = (NumJobStarts>=1 && JobStatus == 1)
job_lease_duration = 3600

Queue runnumber from $(Initialdir)/macros/runlist.list

