Executable  = MCscript.sh
Universe    = vanilla
notification= Never
Input       = /dev/null
Arguments       = $(trigger) $(sim) 
Initialdir    = /sphenix/user/samfred/projects/gammajet/treemaking/
Output    = $(Initialdir)/log/$(process).out
Error     = $(Initialdir)/log/$(process).err
Log       = /tmp/samfred/$(process).log
PeriodicHold  = (NumJobStarts>=1 && JobStatus == 1)
job_lease_duration = 3600

Queue trigger, sim from ranges.list

